### PR TITLE
CP-968 Release w_service 1.1.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-968

JIRA and PR's included in this release: 

 CP-1229  - update tooling, w_service  - https://github.com/Workiva/w_service/pull/70

======= w_service 1.1.0 items =======

 CP-2270  - Deprecate w_service library.  - https://github.com/Workiva/w_service/pull/71
======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_service/compare/1.0.2...CP-968_release_1.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_service/compare/1.0.2...1.1.0

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
