### PR TITLE
CP-959 Remove <br>s from README

### LINKED ISSUE #51: Don't use <br>s in readme (they don't render on pub)

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Fixes #51 

## Changes
- Removes `<br>`s from the README since they don't render on pub.dartlang.org
- Add `.packages` to `.gitignore`

## Areas of Regression
n/a

## Testing
n/a

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf docs only change

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA +1 (doc change only)

Merging into master

**Pull request merged**
