### PR TITLE
CP-723 Release w_service 1.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-723

JIRA and PR's included in this release: 

 CP-729  - Use version ranges compatible with older pub  - https://github.com/Workiva/w_service/pull/48

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_service/compare/1.0.0...CP-723_release_1.0.1

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
