### PR TITLE
CP-706 Setup Travis CI, w_service

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- w_service has been made public and needs to have Travis CI setup
- #29 

## Changes
- `.travis.yml` added
- Badge added to readme

## Areas of Regression
- n/a

## Testing
- Travis CI build passes.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - travis build successful and badge pointing to correct branch
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
