### PR TITLE
CP-939 Add sdk constraint to pubspec, w_service

### LINKED ISSUE #49: Add sdk constraint

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
Fixes #49 - Need an sdk-constraint for this project.

## Changes
Add `>=1.9.0 <2.0.0` sdk constraint.

## Areas of Regression
- Pub publishing

## Testing
- `pub publish --dry-run` produces no warnings.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that 'pub publish --dry-run' produced no errors
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
