### PR TITLE
CP-1229 update tooling, w_service

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- add docs badge
- updated run of dart format
- updated to latest doc generation script

## Changes
**Source:**
- updated run of dart format (whitespace only changes)

**Tests:**
- none

## Areas of Regression
- none

## Testing
- doc gen works as expected

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1 @jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - doc generation still working as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
