### PR TITLE
CP-732 Release w_service 1.0.2

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-732

JIRA and PR's included in this release: 

 CP-866  - Update provider id to be final, retain withCredentials state when forking provider  - https://github.com/Workiva/w_service/pull/61
 CP-939  - Add sdk constraint to pubspec, w_service  - https://github.com/Workiva/w_service/pull/64
 CP-959  - Remove <br>s from README  - https://github.com/Workiva/w_service/pull/65
 CP-928  - Use dart_dev for tooling, w_service  - https://github.com/Workiva/w_service/pull/62
 CP-938  - CSRF interceptor updates  - https://github.com/Workiva/w_service/pull/63

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_service/compare/1.0.1...CP-732_release_1.0.2

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
