### PR TITLE
CP-617 Release w_Service 1.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-617

JIRA and PR's included in this release: 

 CP-619  - Test Coverage, Documentation, Example  - https://github.com/Workiva/w_service/pull/2
 CP-659  - Update documentation w_service  - https://github.com/Workiva/w_service/pull/3
 CP-677  - Add diagnostic tool & example  - https://github.com/Workiva/w_service/pull/15
 CP-679  - Preserve content-type header if already set  - https://github.com/Workiva/w_service/pull/19
 CP-680  - Export WRequest and WResponse from w_transport  - https://github.com/Workiva/w_service/pull/20
 CP-682  - CsrfInterceptor dont overwrite the CSRF header if already set. w_service  - https://github.com/Workiva/w_service/pull/23
 CP-686  - cancelled to canceled, w_service  - https://github.com/Workiva/w_service/pull/24
 CP-689  - Drop unnecessary `this` usages.  - https://github.com/Workiva/w_service/pull/26
 CP-690  - Use package: imports instead of relative  - https://github.com/Workiva/w_service/pull/27
 CP-695  - Add dart analyzer tool, w_service  - https://github.com/Workiva/w_service/pull/28
 CP-696  - Consistent organization of class members.  - https://github.com/Workiva/w_service/pull/32
 CP-700  - Add description and authors to pubspec.yaml  - https://github.com/Workiva/w_service/pull/35
 CP-701  - Add dartfmt check to CI build, w_service  - https://github.com/Workiva/w_service/pull/34
 CP-703  - Add licenses, w_service  - https://github.com/Workiva/w_service/pull/37
 CP-706  - Setup Travis CI, w_service  - https://github.com/Workiva/w_service/pull/39
 CP-710  - Add CHANGELOG.md, w_service  - https://github.com/Workiva/w_service/pull/41
 CP-708  - Refactor HttpContext to add direct support for retry and cancellation info  - https://github.com/Workiva/w_service/pull/40
 CP-709  - Update HttpProvider dispatchers to take optional headers  - https://github.com/Workiva/w_service/pull/38
 CP-718  - Expose WHttpException from w_transport  - https://github.com/Workiva/w_service/pull/44
 CP-721  - Temporarily remove coverage dependencies, w_service.  - https://github.com/Workiva/w_service/pull/42

Diff Between Last Tag and Proposed Release: N/A

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
