### PR TITLE
CP-710 Add CHANGELOG.md, w_service

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
- #14 

## Changes
- Added initial CHANGELOG.md

## Areas of Regression
- n/a

## Testing
- CI build passes.

## Code Review
@trentgrover-wf
@maxwellpeterson-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge, docs only change.

**Comment by jayudey-wf** [comment]
QA + 1 (doc change only)

Merging into master

**Pull request merged**
